/*
 * Generated by dtrace(1M).
 */

#ifndef	_PYDTRACE_H
#define	_PYDTRACE_H

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED
#include <unistd.h>

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */

#ifdef	__cplusplus
extern "C" {
#endif

#define PYTHON_STABILITY "___dtrace_stability$python$v1$4_4_5_4_4_5_4_4_5_4_4_5_4_4_5"

#define PYTHON_TYPEDEFS "___dtrace_typedefs$python$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	PYTHON_FUNCTION_ENTRY(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " PYTHON_TYPEDEFS); \
	__dtrace_probe$python$function__entry$v1$63686172202a$63686172202a$696e74$696e74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " PYTHON_STABILITY); \
} while (0)
#define	PYTHON_FUNCTION_ENTRY_ENABLED() \
	({ int _r = __dtrace_isenabled$python$function__entry$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	PYTHON_FUNCTION_RETURN(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " PYTHON_TYPEDEFS); \
	__dtrace_probe$python$function__return$v1$63686172202a$63686172202a$63686172202a(arg0, arg1, arg2); \
	__asm__ volatile(".reference " PYTHON_STABILITY); \
} while (0)
#define	PYTHON_FUNCTION_RETURN_ENABLED() \
	({ int _r = __dtrace_isenabled$python$function__return$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$python$function__entry$v1$63686172202a$63686172202a$696e74$696e74(const char *, const char *, int, int);
extern int __dtrace_isenabled$python$function__entry$v1(void);
extern void __dtrace_probe$python$function__return$v1$63686172202a$63686172202a$63686172202a(const char *, const char *, const char *);
extern int __dtrace_isenabled$python$function__return$v1(void);

#else

#define	PYTHON_FUNCTION_ENTRY(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	PYTHON_FUNCTION_ENTRY_ENABLED() (0)
#define	PYTHON_FUNCTION_RETURN(arg0, arg1, arg2) \
do { \
	} while (0)
#define	PYTHON_FUNCTION_RETURN_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _PYDTRACE_H */
